name: trigger workflows

on:
  workflow_dispatch:
  issues:
    types:
      - opened
    
jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: master issue workflow
      uses: ./add-feature-to-feature-project.yml
