name: trigger workflows

on:
  workflow_dispatch:
  issues:
    types:
      - opened
    
jobs:
  call-reusable-workflow:
    uses: splitscale/.github/.github/workflows/add-feature-to-feature-project.yml@main
